### ISSUE TITLE
Land-locked developing countries

### ISSUE THREAD

**Issue by mljeffery** [openclimatedata/countrygroups#3]
Request to add the LLDCs group :)

http://unohrlls.org/about-lldcs/
https://en.wikipedia.org/wiki/Landlocked_developing_countries

 Botswana
 Burkina Faso
 Burundi
 Central African Republic
 Chad
 Ethiopia
 Lesotho
 Malawi
 Mali
 Niger
 Rwanda
 South Sudan
 Swaziland
 Uganda
 Zambia
 Zimbabwe
 Afghanistan
 Bhutan
 Kazakhstan
 Kyrgyzstan
 Laos
 Mongolia
 Nepal
 Tajikistan
 Turkmenistan
 Uzbekistan
 Armenia
 Azerbaijan
 Macedonia
 Moldova
 Bolivia
 Paraguay

**Comment by rgieseke** [comment]
Thanks for the request! Included in v0.5.0
