### ISSUE TITLE
Add Montreal Protocol groupings?

### ISSUE THREAD

**Issue by louispotok** [openclimatedata/countrygroups#5]
The Montreal Protocol and Kigali Amendment divide the world's countries into a few groups with different ODS/refrigerant phasedown responsibilities. I think this grouping would be a good fit for inclusion.

Going off [this factsheet](https://multimedia.3m.com/mws/media/1365924O/unep-fact-sheet-kigali-amendment-to-mp.pdf), I see the following 4 mutually-exclusive groups:
1. Non-article 5 countries
  a.  Main group
  b. different baseline calculation: `Belarus, the Russian Federation, Kazakhstan, Tajikistan, and Uzbekistan`.
2. Article 5 countries
  a. Group 1: Most Article 5 countries.
  b. Group 2: `Bahrain, India, Iran, Iraq, Kuwait, Oman, Pakistan, Qatar, Saudi Arabia, and the United Arab Emirates`. 

There is also a "high ambient temperature exemption" for the following countries: `Algeria, Bahrain, Benin, Burkina Faso, Central
African Republic, Chad, Cote d'Ivoire, Djibouti, Egypt, Eritrea, Gambia, Ghana, Guinea, Guinea-Bissau, Iran, Iraq, Jordan, Kuwait, Libya, Mali, Mauritania, Niger, Nigeria, Oman, Pakistan, Qatar, Saudi Arabia, Senegal, Sudan, Syria,
Togo, Tunisia, Turkmenistan and United Arab Emirates`. I think these are all Article 5 countries, but I'm not sure.

Unfortunately, I can't find a perfect reference for exactly which countries are in Article 5.

[This page](https://nou.gov.pk/montreal-protocol/article-5-parties/) from Pakistan's National Ozone Unit has a list of Article 5 countries, and [Wikipedia's page on the Montreal Protocol](https://en.wikipedia.org/wiki/Montreal_Protocol#Multilateral_Fund) says "147 of the 196 Parties to the Montreal Protocol meet these criteria (they are referred to as Article 5 countries)" but I don't see a citation for those numbers.

The closest thing I can find is [UNEP's Ozonaction Networks page](https://www.unep.org/ozonaction/networks) which has a table of regional networks of Ozone Officers. When I copy the table out of a PDF and cleanup the multi-line countries I get 147 (in a gist [here](https://gist.github.com/louispotok/7fbda832910d661a00c51e990a457af1)), so that matches. But I don't know if that's an acceptable source for this repo. I could also see a case for adding each of these regions as a group if it doesn't line up with another regional grouping in the repo, I didn't check that.

Hope this is helpful, happy to help in any other way if I can.

**Comment by louispotok** [comment]
Found it, thanks to a helpful email reply from UNEP:
* [Article 5 / Non-Article 5 status](https://ozone.unep.org/classification-parties)
* [Group 1 and 2 and high-ambient-temperature classification](https://ozone.unep.org/treaties/montreal-protocol/meetings/twenty-eighth-meeting-parties/decisions/decision-xxviii2-decision-related-amendment-phasing-down-hydrofluorocarbons)

**Comment by rgieseke** [comment]
Released as 0.12.0.
Thanks for making it easy to review and fixing the other issues as well!

**Comment by louispotok** [comment]
Thanks for your work on the repo and your help getting this merged!
